#FILENAME:src/main/resources/application.yml:merge
spring:
  application:
    name: {{lowercase data.metadata.name}}
{{#consumes 'kapeta/resource-type-postgresql'}}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
{{/consumes}}