#FILENAME:src/main/resources/application.yml:create-only
spring:
  application:
    name: {{lowercase data.metadata.name}}
{{#consumes 'kapeta/resource-type-mongodb'}}
  data:
    mongodb:
      auto-index-creation: true
{{/consumes}}
{{#consumes 'kapeta/resource-type-postgresql'}}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
{{/consumes}}
{{#consumes 'kapeta/resource-type-mongodb'}}
mongock:
  transaction-strategy: change_unit
  transaction-enabled: true
  migration-scan-package:
    {{#consumers-of-type 'kapeta/resource-type-mongodb'}}
    - "{{string (packageName ../options.basePackage)}}.repositories.{{string (packageName metadata.name)}}.migrations"
    {{/consumers-of-type}}
{{/consumes}}